### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by andrewMacmurray**
Some general cleanup to make elm code more like [PUK project](https://github.com/cast-fuse/parkinsons-and-me)

+ move significant model update logic into `Data` files
+ separate `http` logic into `Request` folder
+ google map div is always in dom, initialised when app is booted but hidden when not on results view
+ rejig css for map and results, results now scroll with main page (fixes offset problems at bottom of page with vh on safari)

### CODE REVIEW

**Review by ivan-unfolds — APPROVED** [review]
You are a coding machine Shmandrew!

**Comment by andrewMacmurray** [comment]
lol

**Comment by andrewMacmurray** [comment]
forgot to mention that the results view on mobile isn't quite fixed yet, will work on that next so we can deploy it again

**Comment by ivan-unfolds** [comment]
Sounds good. Btw yesterday I put some elm tests that we had written into the phoenix test folder. I saw that there is now a `elm/Test` folder, I am guessing this where they should go now?

**Comment by andrewMacmurray** [comment]
yep, that sounds good

**Pull request merged**
