### PR TITLE
Added One Digital Meetup ID

### PR DESCRIPTION
**Pull request by eghale**
@andrewMacmurray @ivanmauricio hopefully this is OK to merge :) 

Took me about 40 minutes to find the right file to add it into (who'd have thought 'controllers' had the data in it! Not me...) but I've now written myself an Evernote walk-through so should be quicker next time!

### CODE REVIEW

**Comment by andrewMacmurray** [comment]
@eghale this looks good, can you remove the `.DS_Store` file? It's a settings file that's generated every time you open the finder window in that folder on a mac (it's not relevant to the project).

It would be great if you could add this this to the `.gitignore` file https://github.com/TechforgoodCAST/tech-for-good-near-you/blob/master/.gitignore, just add the line `.DS_Store` to the bottom of the file 🙏 . Next time anyone commits files these will be automatically ignored

Thanks 😄

**Comment by eghale** [comment]
Cool, done I think? :) @andrewMacmurray

**Review by andrewMacmurray — APPROVED** [review]
looks good 👍

**Comment by eghale** [comment]
woop thanks 😄

**Pull request merged**
